version: "2.10.2"

services:
  database:
    image: postgres
    container_name: alucardb
    restart: always
    ports:
    - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=alucar
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: alucar
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
     - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
