version: '3.1'

services:
  database:
    image: postgres
    container_name: alucar-db
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=alucar
    volumes:
      - pgdata:/data/postgres
    networks:
      - base

  api:
    image: node:16-alpine
    container_name: alucar-api
    working_dir: /usr/src/app
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - ./package.json:/usr/src/app/package.json
      - .:/usr/src/app
    networks:
      - base
    depends_on:
      - database
    command: sh -c "yarn && yarn dev"

volumes:
  pgdata:

networks:
  base:
